name: Disable caching

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14' # or any version you prefer
        # cache: 'npm' (disable caching)

    - name: Install dependencies
      run: npm install
    - name: Run script
      run: node index.js