name: Disable caching

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # or any version you prefer
        cache: 'npm' # to enable caching
        
        cache-dependency-path: 'package.json' 
    - name: Install dependencies
      run: npm install --no-package-lock

    - name: test
      run: npm test
    
    
